/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'

const AboutLazyRouteImport = createFileRoute('/about')()
const AuthenticatedIndexLazyRouteImport = createFileRoute('/_authenticated/')()
const AuthenticatedCargue_masivoLazyRouteImport = createFileRoute(
  '/_authenticated/cargue_masivo',
)()
const AuthenticatedTrazabilidadLazyRouteImport = createFileRoute(
  '/_authenticated/trazabilidad',
)()
const AuthenticatedUsuariosLazyRouteImport = createFileRoute(
  '/_authenticated/usuarios',
)()
const AuthenticatedDiademasIndexLazyRouteImport = createFileRoute(
  '/_authenticated/diademas/',
)()
const AuthenticatedDiademasCreateLazyRouteImport = createFileRoute(
  '/_authenticated/diademas/create',
)()
const AuthenticatedEquiposIndexLazyRouteImport = createFileRoute(
  '/_authenticated/equipos/',
)()
const AuthenticatedEquiposCreateLazyRouteImport = createFileRoute(
  '/_authenticated/equipos/create',
)()
const AuthenticatedInventarioIndexLazyRouteImport = createFileRoute(
  '/_authenticated/inventario/',
)()
const AuthenticatedInventarioIdLazyRouteImport = createFileRoute(
  '/_authenticated/inventario/$id',
)()
const AuthenticatedMonitoresIndexLazyRouteImport = createFileRoute(
  '/_authenticated/monitores/',
)()
const AuthenticatedMonitoresCreateLazyRouteImport = createFileRoute(
  '/_authenticated/monitores/create',
)()
const AuthenticatedPortatilesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/portatiles/',
)()
const AuthenticatedPortatilesCreateLazyRouteImport = createFileRoute(
  '/_authenticated/portatiles/create',
)()
const AuthenticatedPortatilesEvidenciaLazyRouteImport = createFileRoute(
  '/_authenticated/portatiles/evidencia',
)()
const AuthenticatedSopladoIndexLazyRouteImport = createFileRoute(
  '/_authenticated/soplado/',
)()
const AuthenticatedSopladoCreateLazyRouteImport = createFileRoute(
  '/_authenticated/soplado/create',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.index.lazy').then((d) => d.Route),
)
const AuthenticatedCargue_masivoLazyRoute =
  AuthenticatedCargue_masivoLazyRouteImport.update({
    id: '/cargue_masivo',
    path: '/cargue_masivo',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.cargue_masivo.lazy').then((d) => d.Route),
  )
const AuthenticatedTrazabilidadLazyRoute =
  AuthenticatedTrazabilidadLazyRouteImport.update({
    id: '/trazabilidad',
    path: '/trazabilidad',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.trazabilidad.lazy').then((d) => d.Route),
  )
const AuthenticatedUsuariosLazyRoute =
  AuthenticatedUsuariosLazyRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.usuarios.lazy').then((d) => d.Route),
  )
const AuthenticatedDiademasIndexLazyRoute =
  AuthenticatedDiademasIndexLazyRouteImport.update({
    id: '/diademas/',
    path: '/diademas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.diademas.index.lazy').then((d) => d.Route),
  )
const AuthenticatedDiademasCreateLazyRoute =
  AuthenticatedDiademasCreateLazyRouteImport.update({
    id: '/diademas/create',
    path: '/diademas/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.diademas.create.lazy').then((d) => d.Route),
  )
const AuthenticatedEquiposIndexLazyRoute =
  AuthenticatedEquiposIndexLazyRouteImport.update({
    id: '/equipos/',
    path: '/equipos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.equipos.index.lazy').then((d) => d.Route),
  )
const AuthenticatedEquiposCreateLazyRoute =
  AuthenticatedEquiposCreateLazyRouteImport.update({
    id: '/equipos/create',
    path: '/equipos/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.equipos.create.lazy').then((d) => d.Route),
  )
const AuthenticatedInventarioIndexLazyRoute =
  AuthenticatedInventarioIndexLazyRouteImport.update({
    id: '/inventario/',
    path: '/inventario/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.inventario.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedInventarioIdLazyRoute =
  AuthenticatedInventarioIdLazyRouteImport.update({
    id: '/inventario/$id',
    path: '/inventario/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.inventario.$id.lazy').then((d) => d.Route),
  )
const AuthenticatedMonitoresIndexLazyRoute =
  AuthenticatedMonitoresIndexLazyRouteImport.update({
    id: '/monitores/',
    path: '/monitores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.monitores.index.lazy').then((d) => d.Route),
  )
const AuthenticatedMonitoresCreateLazyRoute =
  AuthenticatedMonitoresCreateLazyRouteImport.update({
    id: '/monitores/create',
    path: '/monitores/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.monitores.create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedPortatilesIndexLazyRoute =
  AuthenticatedPortatilesIndexLazyRouteImport.update({
    id: '/portatiles/',
    path: '/portatiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.portatiles.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedPortatilesCreateLazyRoute =
  AuthenticatedPortatilesCreateLazyRouteImport.update({
    id: '/portatiles/create',
    path: '/portatiles/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.portatiles.create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedPortatilesEvidenciaLazyRoute =
  AuthenticatedPortatilesEvidenciaLazyRouteImport.update({
    id: '/portatiles/evidencia',
    path: '/portatiles/evidencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.portatiles.evidencia.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSopladoIndexLazyRoute =
  AuthenticatedSopladoIndexLazyRouteImport.update({
    id: '/soplado/',
    path: '/soplado/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.soplado.index.lazy').then((d) => d.Route),
  )
const AuthenticatedSopladoCreateLazyRoute =
  AuthenticatedSopladoCreateLazyRouteImport.update({
    id: '/soplado/create',
    path: '/soplado/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.soplado.create.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexLazyRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/cargue_masivo': typeof AuthenticatedCargue_masivoLazyRoute
  '/trazabilidad': typeof AuthenticatedTrazabilidadLazyRoute
  '/usuarios': typeof AuthenticatedUsuariosLazyRoute
  '/diademas/create': typeof AuthenticatedDiademasCreateLazyRoute
  '/equipos/create': typeof AuthenticatedEquiposCreateLazyRoute
  '/inventario/$id': typeof AuthenticatedInventarioIdLazyRoute
  '/monitores/create': typeof AuthenticatedMonitoresCreateLazyRoute
  '/portatiles/create': typeof AuthenticatedPortatilesCreateLazyRoute
  '/portatiles/evidencia': typeof AuthenticatedPortatilesEvidenciaLazyRoute
  '/soplado/create': typeof AuthenticatedSopladoCreateLazyRoute
  '/diademas/': typeof AuthenticatedDiademasIndexLazyRoute
  '/equipos/': typeof AuthenticatedEquiposIndexLazyRoute
  '/inventario/': typeof AuthenticatedInventarioIndexLazyRoute
  '/monitores/': typeof AuthenticatedMonitoresIndexLazyRoute
  '/portatiles/': typeof AuthenticatedPortatilesIndexLazyRoute
  '/soplado/': typeof AuthenticatedSopladoIndexLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/cargue_masivo': typeof AuthenticatedCargue_masivoLazyRoute
  '/trazabilidad': typeof AuthenticatedTrazabilidadLazyRoute
  '/usuarios': typeof AuthenticatedUsuariosLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/diademas/create': typeof AuthenticatedDiademasCreateLazyRoute
  '/equipos/create': typeof AuthenticatedEquiposCreateLazyRoute
  '/inventario/$id': typeof AuthenticatedInventarioIdLazyRoute
  '/monitores/create': typeof AuthenticatedMonitoresCreateLazyRoute
  '/portatiles/create': typeof AuthenticatedPortatilesCreateLazyRoute
  '/portatiles/evidencia': typeof AuthenticatedPortatilesEvidenciaLazyRoute
  '/soplado/create': typeof AuthenticatedSopladoCreateLazyRoute
  '/diademas': typeof AuthenticatedDiademasIndexLazyRoute
  '/equipos': typeof AuthenticatedEquiposIndexLazyRoute
  '/inventario': typeof AuthenticatedInventarioIndexLazyRoute
  '/monitores': typeof AuthenticatedMonitoresIndexLazyRoute
  '/portatiles': typeof AuthenticatedPortatilesIndexLazyRoute
  '/soplado': typeof AuthenticatedSopladoIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/_authenticated/cargue_masivo': typeof AuthenticatedCargue_masivoLazyRoute
  '/_authenticated/trazabilidad': typeof AuthenticatedTrazabilidadLazyRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/_authenticated/diademas/create': typeof AuthenticatedDiademasCreateLazyRoute
  '/_authenticated/equipos/create': typeof AuthenticatedEquiposCreateLazyRoute
  '/_authenticated/inventario/$id': typeof AuthenticatedInventarioIdLazyRoute
  '/_authenticated/monitores/create': typeof AuthenticatedMonitoresCreateLazyRoute
  '/_authenticated/portatiles/create': typeof AuthenticatedPortatilesCreateLazyRoute
  '/_authenticated/portatiles/evidencia': typeof AuthenticatedPortatilesEvidenciaLazyRoute
  '/_authenticated/soplado/create': typeof AuthenticatedSopladoCreateLazyRoute
  '/_authenticated/diademas/': typeof AuthenticatedDiademasIndexLazyRoute
  '/_authenticated/equipos/': typeof AuthenticatedEquiposIndexLazyRoute
  '/_authenticated/inventario/': typeof AuthenticatedInventarioIndexLazyRoute
  '/_authenticated/monitores/': typeof AuthenticatedMonitoresIndexLazyRoute
  '/_authenticated/portatiles/': typeof AuthenticatedPortatilesIndexLazyRoute
  '/_authenticated/soplado/': typeof AuthenticatedSopladoIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/cargue_masivo'
    | '/trazabilidad'
    | '/usuarios'
    | '/diademas/create'
    | '/equipos/create'
    | '/inventario/$id'
    | '/monitores/create'
    | '/portatiles/create'
    | '/portatiles/evidencia'
    | '/soplado/create'
    | '/diademas/'
    | '/equipos/'
    | '/inventario/'
    | '/monitores/'
    | '/portatiles/'
    | '/soplado/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/cargue_masivo'
    | '/trazabilidad'
    | '/usuarios'
    | '/'
    | '/diademas/create'
    | '/equipos/create'
    | '/inventario/$id'
    | '/monitores/create'
    | '/portatiles/create'
    | '/portatiles/evidencia'
    | '/soplado/create'
    | '/diademas'
    | '/equipos'
    | '/inventario'
    | '/monitores'
    | '/portatiles'
    | '/soplado'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/about'
    | '/_authenticated/cargue_masivo'
    | '/_authenticated/trazabilidad'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/_authenticated/diademas/create'
    | '/_authenticated/equipos/create'
    | '/_authenticated/inventario/$id'
    | '/_authenticated/monitores/create'
    | '/_authenticated/portatiles/create'
    | '/_authenticated/portatiles/evidencia'
    | '/_authenticated/soplado/create'
    | '/_authenticated/diademas/'
    | '/_authenticated/equipos/'
    | '/_authenticated/inventario/'
    | '/_authenticated/monitores/'
    | '/_authenticated/portatiles/'
    | '/_authenticated/soplado/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cargue_masivo': {
      id: '/_authenticated/cargue_masivo'
      path: '/cargue_masivo'
      fullPath: '/cargue_masivo'
      preLoaderRoute: typeof AuthenticatedCargue_masivoLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trazabilidad': {
      id: '/_authenticated/trazabilidad'
      path: '/trazabilidad'
      fullPath: '/trazabilidad'
      preLoaderRoute: typeof AuthenticatedTrazabilidadLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diademas/': {
      id: '/_authenticated/diademas/'
      path: '/diademas'
      fullPath: '/diademas/'
      preLoaderRoute: typeof AuthenticatedDiademasIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diademas/create': {
      id: '/_authenticated/diademas/create'
      path: '/diademas/create'
      fullPath: '/diademas/create'
      preLoaderRoute: typeof AuthenticatedDiademasCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipos/': {
      id: '/_authenticated/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof AuthenticatedEquiposIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipos/create': {
      id: '/_authenticated/equipos/create'
      path: '/equipos/create'
      fullPath: '/equipos/create'
      preLoaderRoute: typeof AuthenticatedEquiposCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventario/': {
      id: '/_authenticated/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof AuthenticatedInventarioIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventario/$id': {
      id: '/_authenticated/inventario/$id'
      path: '/inventario/$id'
      fullPath: '/inventario/$id'
      preLoaderRoute: typeof AuthenticatedInventarioIdLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitores/': {
      id: '/_authenticated/monitores/'
      path: '/monitores'
      fullPath: '/monitores/'
      preLoaderRoute: typeof AuthenticatedMonitoresIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitores/create': {
      id: '/_authenticated/monitores/create'
      path: '/monitores/create'
      fullPath: '/monitores/create'
      preLoaderRoute: typeof AuthenticatedMonitoresCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portatiles/': {
      id: '/_authenticated/portatiles/'
      path: '/portatiles'
      fullPath: '/portatiles/'
      preLoaderRoute: typeof AuthenticatedPortatilesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portatiles/create': {
      id: '/_authenticated/portatiles/create'
      path: '/portatiles/create'
      fullPath: '/portatiles/create'
      preLoaderRoute: typeof AuthenticatedPortatilesCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portatiles/evidencia': {
      id: '/_authenticated/portatiles/evidencia'
      path: '/portatiles/evidencia'
      fullPath: '/portatiles/evidencia'
      preLoaderRoute: typeof AuthenticatedPortatilesEvidenciaLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/soplado/': {
      id: '/_authenticated/soplado/'
      path: '/soplado'
      fullPath: '/soplado/'
      preLoaderRoute: typeof AuthenticatedSopladoIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/soplado/create': {
      id: '/_authenticated/soplado/create'
      path: '/soplado/create'
      fullPath: '/soplado/create'
      preLoaderRoute: typeof AuthenticatedSopladoCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCargue_masivoLazyRoute: typeof AuthenticatedCargue_masivoLazyRoute
  AuthenticatedTrazabilidadLazyRoute: typeof AuthenticatedTrazabilidadLazyRoute
  AuthenticatedUsuariosLazyRoute: typeof AuthenticatedUsuariosLazyRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
  AuthenticatedDiademasCreateLazyRoute: typeof AuthenticatedDiademasCreateLazyRoute
  AuthenticatedEquiposCreateLazyRoute: typeof AuthenticatedEquiposCreateLazyRoute
  AuthenticatedInventarioIdLazyRoute: typeof AuthenticatedInventarioIdLazyRoute
  AuthenticatedMonitoresCreateLazyRoute: typeof AuthenticatedMonitoresCreateLazyRoute
  AuthenticatedPortatilesCreateLazyRoute: typeof AuthenticatedPortatilesCreateLazyRoute
  AuthenticatedPortatilesEvidenciaLazyRoute: typeof AuthenticatedPortatilesEvidenciaLazyRoute
  AuthenticatedSopladoCreateLazyRoute: typeof AuthenticatedSopladoCreateLazyRoute
  AuthenticatedDiademasIndexLazyRoute: typeof AuthenticatedDiademasIndexLazyRoute
  AuthenticatedEquiposIndexLazyRoute: typeof AuthenticatedEquiposIndexLazyRoute
  AuthenticatedInventarioIndexLazyRoute: typeof AuthenticatedInventarioIndexLazyRoute
  AuthenticatedMonitoresIndexLazyRoute: typeof AuthenticatedMonitoresIndexLazyRoute
  AuthenticatedPortatilesIndexLazyRoute: typeof AuthenticatedPortatilesIndexLazyRoute
  AuthenticatedSopladoIndexLazyRoute: typeof AuthenticatedSopladoIndexLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCargue_masivoLazyRoute: AuthenticatedCargue_masivoLazyRoute,
  AuthenticatedTrazabilidadLazyRoute: AuthenticatedTrazabilidadLazyRoute,
  AuthenticatedUsuariosLazyRoute: AuthenticatedUsuariosLazyRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
  AuthenticatedDiademasCreateLazyRoute: AuthenticatedDiademasCreateLazyRoute,
  AuthenticatedEquiposCreateLazyRoute: AuthenticatedEquiposCreateLazyRoute,
  AuthenticatedInventarioIdLazyRoute: AuthenticatedInventarioIdLazyRoute,
  AuthenticatedMonitoresCreateLazyRoute: AuthenticatedMonitoresCreateLazyRoute,
  AuthenticatedPortatilesCreateLazyRoute:
    AuthenticatedPortatilesCreateLazyRoute,
  AuthenticatedPortatilesEvidenciaLazyRoute:
    AuthenticatedPortatilesEvidenciaLazyRoute,
  AuthenticatedSopladoCreateLazyRoute: AuthenticatedSopladoCreateLazyRoute,
  AuthenticatedDiademasIndexLazyRoute: AuthenticatedDiademasIndexLazyRoute,
  AuthenticatedEquiposIndexLazyRoute: AuthenticatedEquiposIndexLazyRoute,
  AuthenticatedInventarioIndexLazyRoute: AuthenticatedInventarioIndexLazyRoute,
  AuthenticatedMonitoresIndexLazyRoute: AuthenticatedMonitoresIndexLazyRoute,
  AuthenticatedPortatilesIndexLazyRoute: AuthenticatedPortatilesIndexLazyRoute,
  AuthenticatedSopladoIndexLazyRoute: AuthenticatedSopladoIndexLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AboutLazyRoute: AboutLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
